### *_Умова задачі_*

Використовуючи GaussianNB з бібліотеки Scikit-Learn створіть модель класифікації для навчання з використанням дата сету 
Iris (sklearn.datasets.load_iris). Після цього, за допомогою методів з бібліотеки ml_metrics обрахуйте метрики для отриманої моделі

In [13]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score


In [14]:
# Завантажуємо  датасет Iris і розділяємо дані на тренувальні і тестові набори
iris = load_iris() 
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 42)


In [15]:
# Навчаємо модель Gaussian Naive Bayes на тренувальних даних і використовуємо її для передбачення на тестових даних
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [16]:
y_pred = model.predict(X_test)


In [17]:
# Обчислюємо метрики з бібліотеки Scikit-Learn
acc = accuracy_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)
prec = precision_score(y_test, y_pred, average='macro')
rec = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

In [18]:
print('Accuracy:', acc)
print('Precision:', prec)
print('Recall:', rec)
print('F1_Score:', f1)
print('Confusion_Matrix:')
print(conf_mat)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1_Score: 1.0
Confusion_Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
